# -*- coding: utf-8 -*-
"""Case1Filtering.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZXtZ0S8XxXcxa-UKc8LN8U8luYb8kXBH
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install pm4py

import pandas as pd
import pm4py

log_df = pd.read_csv('https://raw.githubusercontent.com/paoloceravolo/BIS2022/main/Event%20Logs/CallCenterLog.csv',sep=',')
log_df.rename(columns={'Case ID': 'case:concept:name', 'Start Date': 'start_timestamp', 'End Date': 'time:timestamp', 'Activity': 'concept:name', 'Resource': 'org:resource'}, inplace=True) #change the name to a colum

log_df = pm4py.format_dataframe(log_df, case_id='case:concept:name', activity_key='concept:name', timestamp_key='time:timestamp')
event_log = pm4py.convert_to_event_log(log_df)

filtered_log = pm4py. event_log, 1, 864000)
filtered_log = pm4py.filter_end_activities(filtered_log, ['Inbound Call', 'Handle Case', 'Handle Email'])
filtered_log = pm4py.filter_directly_follows_relation(filtered_log, [('Handle Case','Handle Case'),('Handle Case','Inbound Call')],retain = False)


print(len(event_log))
print(len(filtered_log))

filtered_df = pm4py.convert_to_dataframe(filtered_log)

df_count['Count'] = filtered_df.groupby(['case:concept:name'])['case:concept:name'].count()

df_count

pm4py.view_dotted_chart(filtered_log, format="png")