# -*- coding: utf-8 -*-
"""Case3Filtering.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15JJSkx06DV64PEsD7ALalXlhzavjf3m5
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install pm4py

import pandas as pd
import pm4py

# Preparing data 

log_df = pd.read_csv('https://raw.githubusercontent.com/paoloceravolo/BIS2022/main/Event%20Logs/Road_Traffic_Fine_Management_Process.csv')
log_df = log_df.rename(columns={'Case ID': 'case:concept:name','Complete Timestamp': 'time:timestamp','Activity':'concept:name','Resource': 'org:resource'})
log_df['time:timestamp'] = pd.to_datetime(log_df['time:timestamp'])
#log_df

num_events = len(log_df)
num_cases = len(log_df['case:concept:name'].unique())

start_activities = pm4py.get_start_activities(log_df)
end_activities = pm4py.get_end_activities(log_df)

print("Number of events: {}\nNumber of cases: {}".format(num_events, num_cases))
print("Start activties: {}\nEnd activities: {}\n".format(start_activities, end_activities))