# -*- coding: utf-8 -*-
"""Case2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1r1wH6OTbUdXS47Eof_PUm3GvCQfTmPxi
"""

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import random
import seaborn as sns

regions = ['Italy', 'France', 'Switzerland', 'Austria', 'Slovenia']
sold = [30, 24, 23, 19, 12]
pv = [150, 140, 130, 150, 155]

data = {'Regions': regions, 'Sold': sold}

df = pd.DataFrame(data, index=regions)

gen_value_2021 = [v*pv[i] for i,v in enumerate(df['Sold'])]

print(gen_value_2021)

plt.bar(df['Regions'], gen_value_2021, color='green')
plt.xlabel("")
plt.ylabel("Product Sold")
plt.title("Sold per region")

plt.show()

topics = ['Analgesics', 'Antibiotic', 'Anticoagulant', 'Antidepressant', 'Anticancer', 'Antiepileptic']

df_2022 = pd.DataFrame(np.random.randint(2,size=(100, 6)), columns=list(topics))

df_2022['Total'] = df_2022.sum(axis=1)
df_2022['Region'] = random.choices(regions, k=100)

group = df_2022.groupby('Region').agg('sum')

#print(group)

gen_value_2022 = [v*pv[i] for i,v in enumerate(group['Total'])]

#print(gen_value_2022)

sns.heatmap(group, vmin=0, vmax=30, cmap="Reds", linewidths=0.5, annot=True)

# positions of the elements in an array
ind = np.arange(len(regions))

print(ind)

width = 0.4
# first the x-axis, second the y-axis, we use ind for refering to the position only
plt.bar(ind, gen_value_2021, width, label='Generated value 2021')
# ind+width moves the following bar of a space equal to width 
plt.bar(ind+width, gen_value_2022, width, label='Generated value 2022')
plt.xlabel("Regions")
plt.ylabel("Products Sold")
plt.title("Sold per region and generated value")

# Get or set the current tick locations and labels of the x-axis.
plt.xticks(ind + width /2, df_2021['Region'])
plt.legend(loc='best')
plt.show()