# -*- coding: utf-8 -*-
"""DiscoveryTest.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1O2VH_U_qkB9Rfn1eefpo1bsM4gGlxpCb
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
# %pip install pm4py
import pm4py
from pm4py.objects.log.util import dataframe_utils
from pm4py.objects.conversion.log import converter as log_converter

import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt

from google.colab import files
file = files.upload()

log_df = pd.read_csv('test.csv',sep=',')
log_df['time:timestamp']= pd.to_datetime(log_df['time:timestamp'])

## Alpha_miner algorithm
net, im, fm = pm4py.discover_petri_net_alpha(log_df)

# Visualise 
pm4py.view_petri_net(net, im, fm, format='png')

# Discover petri net using heuristics miner

net, im, fm = pm4py.discover_petri_net_heuristics(log_df, and_threshold = 0.9)

pm4py.view_petri_net(net, im, fm, format='png')

# Discover petri net using inductive miner
net, im, fm = pm4py.discover_petri_net_inductive(log_df)

pm4py.view_petri_net(net, im, fm, format='png')

# Discover petri net using  Integer Linear Programming

net, im, fm = pm4py.discover_petri_net_ilp(log_df)

pm4py.view_petri_net(net, im, fm, format='png')