# -*- coding: utf-8 -*-
"""Case5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Sm3_vMWGDD8ZIrxaOVvCaht7-kWfVY4W
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
# %pip install pm4py
import pm4py

import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt

# Preparing data

## Let's import the event log dataset in a pandas dataframe
### pm4py uses dataframe as the standard format for event logs

log_df = pd.read_csv('https://raw.githubusercontent.com/paoloceravolo/BIS2022/main/Event%20Logs/sepsis%20cases%20-%20event%20log.csv',sep=',')
log_df['@@case_index'] = log_df['@@case_index'].apply(str)
log_df.rename(columns={'@@case_index': 'case:concept:name', 'case:concept:name': 'Case Name'}, inplace=True) #change the name to a colum
log_df['time:timestamp']= pd.to_datetime(log_df['time:timestamp'])

num_events = len(log_df)
num_cases = len(log_df['case:concept:name'].unique())
print("Number of events: {}\nNumber of cases: {}".format(num_events, num_cases))

start_activities = pm4py.get_start_activities(log_df)
end_activities = pm4py.get_end_activities(log_df)
print("Start activities: {}\nEnd activities: {}".format(start_activities, end_activities))

#log_df

# Incomplete cases

## Let's consider incomplete all cases not ending with a legal end activity like Payment or Send for Credit Collection

filtered_log = pm4py.filter_end_activities(log_df, ['Release A', 'Release B', 'Release C', 'Release D', 'Release E', 'Return ER'])
filtered_log = pm4py.filter_start_activities(filtered_log, ['ER Registration', 'ER Sepsis Triage', 'ER Triage'])
                                           
print("Given {} total cases in the log we have {} cases that comply with the applied filter".format(len(log_df['case:concept:name'].unique()), len(filtered_log['case:concept:name'].unique())))
#print("The cycle time of the entire log is {} while the cycle time of the cases that comply with the applied filter is {}".format(cycle_time_log, cycle_time_filtered_log))

#variants = pm4py.get_variants_as_tuples(filtered_log)
#variants

# Discover petri net using inductive miner
net, im, fm = pm4py.discover_petri_net_heuristics(filtered_log, dependency_threshold=0.9, and_threshold=0.6, loop_two_threshold=0.7)
pm4py.view_petri_net(net, im, fm, format='png')

# Discover BPMN net using inductive miner
#bpmn_graph = pm4py.discover_bpmn_inductive(filtered_log)
#pm4py.view_bpmn(bpmn_graph)

# Create a segmend by taking cases having CRP value at leat of 50

segmentCRP50 = filtered_log.groupby('case:concept:name').filter(lambda x: x['CRP'].min() >= 50.)

#alternative code
#cases = filtered_log[filtered_log["CRP"] > 50]["case:concept:name"].unique()
#filtered_log = filtered_log[filtered_log["case:concept:name"].isin(cases)]


print("Given {} total cases in the log we have {} cases that comply with the applied filter".format(len(log_df['case:concept:name'].unique()), len(segmentCRP50['case:concept:name'].unique())))

# Get the end activities of the entire event log
#it returns and object with the occurence for each end activity
end_activities = pm4py.get_end_activities(log_df)
cases_end_activities = end_activities['Return ER']

# Filter the event log based on how many activites Act are in it
admission = pm4py.filter_activities_rework(log_df, 'Admission NC', 1)
cases_admission = len(admission['case:concept:name'].unique())

# Get the end activities of the segment
end_activities_CRP50 = pm4py.get_end_activities(segmentCRP50)
cases_end_activities_CRP50 = end_activities_CRP50['Return ER']

# Filter the segment log based on how many activites Act are in it
admission_CRP50 = pm4py.filter_activities_rework(segmentCRP50, 'Admission NC', 1)
cases_admission_CRP50 = len(admission_CRP50['case:concept:name'].unique())

cases_log = len(log_df['case:concept:name'].unique())

cases_segment = len(segmentCRP50['case:concept:name'].unique())

print("Given {} total cases in the log we have {} Return ER as end activity: {}".format(cases_log, cases_end_activities, round((cases_end_activities/cases_log), 3)))
print("Given {} cases in the segment we have {} Return ER as end activity: {}. With LIFT: {}".format(cases_segment, cases_end_activities_CRP50, round((cases_end_activities_CRP50/cases_segment), 3), ((cases_end_activities_CRP50/cases_segment)/(cases_end_activities/cases_log))))

print("Given {} total cases in the log we have {} Admission: {}".format(cases_log, cases_admission, round((cases_admission/cases_log), 3)))
print("Given {} cases in the segment we have {} Admission: {}. With LIFT: {}".format(cases_segment, cases_admission_CRP50, round((cases_admission_CRP50/cases_segment), 3), ((cases_admission_CRP50/cases_segment)/(cases_admission/cases_log))))

from scipy.stats import chisquare

#chisquare([(cases_end_activities/cases_log), (cases_end_activities_CRP50/cases_segment)])
chisquare([(cases_admission/cases_log), (cases_admission_CRP50/cases_segment)])